import type { NarrativeOutputData } from "@/types/narrative";
import type { DeckTheme } from "@/components/SlidePreview";
import { CHAR_LIMITS, getHeadlineFontSize, truncate, resolveLayout } from "@/lib/slideLayouts";

interface ExportOptions { output: NarrativeOutputData; isPro: boolean; excludedSlides: Set<number>; slideOrder: number[]; deckTheme: DeckTheme; }
type RGB = [number,number,number];
interface PC { bg:RGB; fg:RGB; primary:RGB; muted:RGB; accent:RGB; }

function getColors(theme: DeckTheme): PC {
  const hex=(h:string):RGB=>{const c=h.replace("#","");return[parseInt(c.substring(0,2),16),parseInt(c.substring(2,4),16),parseInt(c.substring(4,6),16)];};
  if (theme.scheme==="light") return {bg:[255,255,255],fg:[26,26,46],primary:[59,130,246],muted:[107,114,128],accent:[59,130,246]};
  if (theme.scheme==="custom"){const b=hex(theme.secondary||"#0b0f14");const br=(b[0]*299+b[1]*587+b[2]*114)/1000;return{bg:b,fg:br>128?[26,26,46]:[220,224,232],primary:hex(theme.primary||"#3b82f6"),muted:[107,114,128],accent:hex(theme.accent||"#1e3a5f")};}
  return {bg:[11,15,20],fg:[220,224,232],primary:[59,130,246],muted:[107,114,128],accent:[59,130,246]};
}

function pdfHSize(t:string):number{const s=getHeadlineFontSize(t);return s>=24?20:s>=22?18:s>=20?16:14;}
function onA(c:PC):RGB{return [255,255,255];}

function sf(raw:any){
  const headline=truncate(typeof raw==="string"?raw:(raw?.headline||""),CHAR_LIMITS.HEADLINE_MAX);
  const subheadline=truncate(raw?.subheadline||raw?.subheader||"",CHAR_LIMITS.SUBHEADLINE_MAX);
  const bodyContent:string[]=(Array.isArray(raw?.bodyContent)?raw.bodyContent:[]).map((b:string)=>truncate(b.replace(/^[-\u2022*]\s*/,""),CHAR_LIMITS.BULLET_MAX));
  const categoryLabel=truncate(raw?.categoryLabel||"",CHAR_LIMITS.CATEGORY_MAX);
  const closingStatement=truncate(raw?.closingStatement||"",CHAR_LIMITS.CLOSING_MAX);
  const dataPoints:string[]=raw?.metadata?.dataPoints||[];
  return {headline,subheadline,bodyContent,categoryLabel,closingStatement,dataPoints};
}

export async function exportPdf({output,isPro,excludedSlides,slideOrder,deckTheme}:ExportOptions){
  const {jsPDF}=await import("jspdf");
  const title=(output as any).title||"Narrative Deck";
  const c=getColors(deckTheme);
  const pdf=new jsPDF({orientation:"landscape",unit:"in",format:[10,7.5]});
  const W=10,H=7.5,ML=0.75,CW=W-ML*2;
  const sc=(col:RGB,t:"fill"|"text"="text")=>{t==="fill"?pdf.setFillColor(col[0],col[1],col[2]):pdf.setTextColor(col[0],col[1],col[2]);};
  const bg=()=>{sc(c.bg,"fill");pdf.rect(0,0,W,H,"F");sc(c.accent,"fill");pdf.rect(0,0,W,0.04,"F");};

  // Title
  bg(); sc(c.accent,"fill"); pdf.rect(0,H-0.05,W,0.05,"F");
  pdf.setFont("helvetica","bold"); pdf.setFontSize(24); sc(c.primary); pdf.text(title,W/2,3.0,{align:"center"});
  pdf.setFontSize(10); sc(c.muted); pdf.text(output.mode.replace(/_/g," ").toUpperCase(),W/2,3.6,{align:"center"});
  if(!isPro){pdf.setFontSize(8);sc(c.muted);pdf.text("Generated by Rhetoric",W/2,5.8,{align:"center"});}

  // Content
  const d=(output.data||(output as any).supporting||{}) as any;
  const del=(output as any).deliverable||{};
  const fw=d.deckFramework||del.deckFramework||d.boardDeckOutline||del.boardDeckOutline||[];
  const ordered=slideOrder.length>0?slideOrder:fw.map((_:any,i:number)=>i);
  const active=ordered.filter((i:number)=>!excludedSlides.has(i));

  for(const idx of active){
    const raw=fw[idx]; if(!raw) continue;
    pdf.addPage(); bg();
    const f=sf(raw);
    const layout=resolveLayout(raw?.layoutRecommendation,raw?.selectedLayout);
    let y=0.6;

    // Header
    if(f.categoryLabel){pdf.setFont("helvetica","bold");pdf.setFontSize(9);sc(c.accent);pdf.text(f.categoryLabel.toUpperCase(),ML,y);y+=0.28;}
    const hs=pdfHSize(f.headline);pdf.setFont("helvetica","bold");pdf.setFontSize(hs);sc(c.primary);
    const hl=pdf.splitTextToSize(f.headline,CW);pdf.text(hl,ML,y);y+=hl.length*(hs/72*1.3)+0.15;

    if(layout==="statement"){
      if(f.subheadline){pdf.setFont("helvetica","normal");pdf.setFontSize(12);sc(c.muted);pdf.text(pdf.splitTextToSize(f.subheadline,CW*0.75),ML,y+0.3);}
      if(f.closingStatement){sc(c.accent,"fill");pdf.rect(0,H-0.9,W,0.9,"F");pdf.setFont("helvetica","bold");pdf.setFontSize(12);sc(onA(c));pdf.text(f.closingStatement,ML,H-0.45);}
    } else if(layout==="data-cards"||layout==="icon-columns"){
      const items=f.bodyContent.slice(0,3);const dp=f.dataPoints;const n=Math.max(dp.length,Math.min(items.length,3));
      if(n>0){const gap=0.3;const cW=(CW-gap*(n-1))/n;const cH=1.7;
        for(let i=0;i<n;i++){const cx=ML+i*(cW+gap);sc(c.accent,"fill");pdf.roundedRect(cx,y,cW,cH,0.06,0.06,"F");
          if(dp[i]){pdf.setFont("helvetica","bold");pdf.setFontSize(22);sc(onA(c));pdf.text(dp[i],cx+0.2,y+0.5);}
          if(items[i]){pdf.setFont("helvetica","normal");pdf.setFontSize(9);sc(onA(c));pdf.text(pdf.splitTextToSize(truncate(items[i],80),cW-0.4),cx+0.2,y+(dp[i]?0.85:0.3));}
        }y+=cH+0.2;}
      const rest=f.bodyContent.slice(n);
      if(rest.length>0){pdf.setFont("helvetica","normal");pdf.setFontSize(10);for(const l of rest){if(y>H-0.8)break;sc(c.accent);pdf.text("\u2022",ML,y);sc(c.fg);pdf.text(pdf.splitTextToSize(l,CW-0.3),ML+0.25,y);y+=0.3;}}
    } else if(layout==="concentric"){
      const items=f.bodyContent.slice(0,3);const dp=f.dataPoints;const cx=ML+CW*0.6;const cy=y+(H-y-0.6)/2;
      const radii=[1.3,0.9,0.5];
      for(let i=0;i<Math.min(items.length,3);i++){sc(c.accent,"fill");pdf.circle(cx,cy,radii[i],"F");sc(c.primary,"fill");pdf.circle(cx,cy,radii[i],"S");}
      for(let i=0;i<Math.min(items.length,3);i++){
        if(dp[i]){pdf.setFont("helvetica","bold");pdf.setFontSize(i===0?12:10);sc(onA(c));pdf.text(dp[i],cx,cy-radii[i]+0.35,{align:"center"});}
        const ly=y+i*0.55; sc(c.primary);pdf.setFont("helvetica","bold");pdf.setFontSize(11);
        if(dp[i])pdf.text(dp[i],ML,ly+0.15);
        pdf.setFont("helvetica","normal");pdf.setFontSize(9);sc(c.fg);pdf.text(truncate(items[i],50),ML,ly+(dp[i]?0.35:0.15));
      }
    } else if(layout==="matrix"){
      const items=f.bodyContent.slice(0,4);const cols=2;const rows=Math.ceil(items.length/cols);const gap=0.2;
      const cellW=(CW-gap)/cols;const cellH=(H-y-0.6)/rows-gap/2;
      for(let i=0;i<items.length;i++){const col=i%cols;const row=Math.floor(i/cols);const cx2=ML+col*(cellW+gap);const cy2=y+row*(cellH+gap);
        sc(c.accent,"fill");pdf.roundedRect(cx2,cy2,cellW,cellH,0.06,0.06,"F");sc(c.primary,"fill");pdf.rect(cx2,cy2,0.04,cellH,"F");
        pdf.setFont("helvetica","normal");pdf.setFontSize(10);sc(onA(c));pdf.text(pdf.splitTextToSize(truncate(items[i],120),cellW-0.5),cx2+0.2,cy2+0.3);}
    } else if(layout==="timeline"){
      const items=f.bodyContent.slice(0,5);const n=items.length;const sp=CW/n;const r=0.13;
      sc(c.accent,"fill");pdf.rect(ML+sp/2,y+r-0.01,CW-sp,0.02,"F");
      for(let i=0;i<n;i++){const cx2=ML+sp*i+sp/2;sc(c.primary,"fill");pdf.circle(cx2,y+r,r,"F");
        pdf.setFont("helvetica","bold");pdf.setFontSize(9);sc(onA(c));pdf.text(String(i+1),cx2,y+r+0.04,{align:"center"});
        pdf.setFont("helvetica","normal");pdf.setFontSize(9);sc(c.fg);pdf.text(pdf.splitTextToSize(truncate(items[i],70),sp-0.3),cx2,y+r*2+0.2,{align:"center"});}
    } else if(layout==="staircase"){
      const items=f.bodyContent.slice(0,4);const dp=f.dataPoints;const n=items.length;const stepW=CW/n;const maxH=H-y-0.6;const baseY=y+maxH;
      for(let i=0;i<n;i++){const stepH=maxH*((i+1)/n)*0.85;const sx=ML+i*stepW;const sy=baseY-stepH;
        sc(i===n-1?c.primary:c.accent,"fill");pdf.roundedRect(sx+0.05,sy,stepW-0.1,stepH,0.04,0.04,"F");
        if(dp[i]){pdf.setFont("helvetica","bold");pdf.setFontSize(13);sc(onA(c));pdf.text(dp[i],sx+stepW/2,sy+0.25,{align:"center"});}
        pdf.setFont("helvetica","normal");pdf.setFontSize(8);sc(onA(c));pdf.text(pdf.splitTextToSize(truncate(items[i],50),stepW-0.3),sx+stepW/2,sy+(dp[i]?0.45:0.2),{align:"center"});}
    } else if(layout==="team"){
      const items=f.bodyContent.slice(0,3);const n=items.length;const gap=0.25;const cW2=(CW-gap*(n-1))/n;const cH2=H-y-0.6;
      for(let i=0;i<n;i++){const cx2=ML+i*(cW2+gap);sc(c.accent,"fill");pdf.roundedRect(cx2,y,cW2,cH2,0.06,0.06,"F");
        sc(c.primary,"fill");pdf.circle(cx2+cW2/2,y+0.4,0.18,"F");
        const t=items[i];const ci=t.indexOf(":");const title=ci>0?t.substring(0,ci):"";const desc=ci>0?t.substring(ci+1).trim():t;
        if(title){pdf.setFont("helvetica","bold");pdf.setFontSize(10);sc(onA(c));pdf.text(title,cx2+cW2/2,y+0.8,{align:"center"});}
        pdf.setFont("helvetica","normal");pdf.setFontSize(9);sc(onA(c));pdf.text(pdf.splitTextToSize(truncate(desc,90),cW2-0.4),cx2+cW2/2,y+(title?1.0:0.8),{align:"center"});}
    } else {
      // Default bullets
      if(f.subheadline){pdf.setFont("helvetica","normal");pdf.setFontSize(11);sc(c.muted);const sl=pdf.splitTextToSize(f.subheadline,CW);pdf.text(sl,ML,y);y+=sl.length*0.2+0.12;}
      if(f.bodyContent.length>0){pdf.setFont("helvetica","normal");const bs=f.bodyContent.length>4?10:11;pdf.setFontSize(bs);
        for(const l of f.bodyContent.slice(0,6)){if(y>H-0.8)break;sc(c.accent);pdf.text("\u2022",ML,y);sc(c.fg);const w=pdf.splitTextToSize(l,CW-0.3);pdf.text(w,ML+0.25,y);y+=w.length*0.2+0.08;}}
      if(f.closingStatement&&y<H-0.5){pdf.setFont("helvetica","bold");pdf.setFontSize(9);sc(c.accent);pdf.text(f.closingStatement,ML,H-0.55);}
    }
    if(!isPro){pdf.setFontSize(7);sc(c.muted);pdf.text("Generated by Rhetoric",ML,H-0.3);}
  }
  pdf.save(`${title.replace(/[^a-zA-Z0-9 ]/g,"")}.pdf`);
}