import type { NarrativeOutputData } from "@/types/narrative";
import type { DeckTheme } from "@/components/SlidePreview";

interface ExportOptions {
  output: NarrativeOutputData;
  isPro: boolean;
  excludedSlides: Set<number>;
  slideOrder: number[];
  deckTheme: DeckTheme;
}

function getThemeColors(theme: DeckTheme) {
  if (theme.scheme === "light") {
    return { BG: "ffffff", FG: "1a1a2e", MUTED: "6b7280", MUTED_TEXT: "9ca3af", ACCENT: "3b82f6", ACCENT_DIM: "dbeafe" };
  }
  if (theme.scheme === "custom") {
    const strip = (hex: string) => hex.replace("#", "");
    return {
      BG: strip(theme.secondary || "#0b0f14"),
      FG: theme.secondary && parseInt(theme.secondary.replace("#", ""), 16) > 0x888888 ? "1a1a2e" : "dce0e8",
      MUTED: "6b7280",
      MUTED_TEXT: "9ca3af",
      ACCENT: strip(theme.primary || "#3b82f6"),
      ACCENT_DIM: strip(theme.accent || "#1e3a5f"),
    };
  }
  return { BG: "0b0f14", FG: "dce0e8", MUTED: "6b7280", MUTED_TEXT: "9ca3af", ACCENT: "3b82f6", ACCENT_DIM: "1e3a5f" };
}

function headlineFontSize(text: string): number {
  return text.length > 50 ? 24 : 28;
}

const MARGIN_L = 0.75;
const CONTENT_W = 8.5; // 10in - 0.75in * 2

export async function exportPptx({ output, isPro, excludedSlides, slideOrder, deckTheme }: ExportOptions) {
  const PptxGenJS = (await import("pptxgenjs")).default;
  const pptx = new PptxGenJS();
  const title = (output as any).title || "Narrative Deck";
  pptx.author = "Rhetoric";
  pptx.title = title;
  pptx.layout = "LAYOUT_16x9";

  const colors = getThemeColors(deckTheme);
  const { BG, FG, MUTED, MUTED_TEXT, ACCENT } = colors;

  // ── Title slide ──
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: BG };
  titleSlide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: "100%", h: 0.04, fill: { color: ACCENT } });
  titleSlide.addText(title, { x: 0.8, y: 1.8, w: 8.4, h: 1.2, fontSize: 36, fontFace: "Arial", bold: true, color: FG, align: "center", valign: "middle" });
  titleSlide.addText(output.mode.replace(/_/g, " ").toUpperCase(), { x: 0.8, y: 3.2, w: 8.4, fontSize: 14, fontFace: "Arial", color: ACCENT, align: "center", charSpacing: 4 });
  if (!isPro) titleSlide.addText("Generated by Rhetoric", { x: 0.8, y: 5, w: 8.4, fontSize: 10, fontFace: "Arial", color: MUTED, align: "center" });

  // ── Content slides ──
  const d = (output.data || (output as any).supporting || {}) as any;
  const del = (output as any).deliverable || {};
  const framework = d.deckFramework || del.deckFramework || d.boardDeckOutline || del.boardDeckOutline || [];
  const orderedIndices = slideOrder.length > 0 ? slideOrder : framework.map((_: any, i: number) => i);
  const activeIndices = orderedIndices.filter((i: number) => !excludedSlides.has(i));

  for (const originalIdx of activeIndices) {
    const raw = framework[originalIdx];
    if (!raw) continue;

    // Extract structured data from deckFramework
    const headline = typeof raw === "string" ? raw : (raw.headline || "");
    const subheadline = typeof raw === "string" ? "" : (raw.subheadline || raw.subheader || "");
    const bodyContent: string[] = typeof raw === "string" ? [] : (Array.isArray(raw.bodyContent) ? raw.bodyContent : []);
    const speakerNotes = typeof raw === "string" ? "" : (raw.speakerNotes || "");
    const categoryLabel = typeof raw === "string" ? "" : (raw.categoryLabel || "");
    const closingStatement = typeof raw === "string" ? "" : (raw.closingStatement || "");
    const layoutRecommendation = typeof raw === "string" ? "" : (raw.layoutRecommendation || "");

    const slide = pptx.addSlide();
    slide.background = { color: BG };
    slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: "100%", h: 0.04, fill: { color: ACCENT } });

    // Category label (above headline)
    if (categoryLabel) {
      slide.addText(categoryLabel.toUpperCase(), {
        x: MARGIN_L, y: 0.25, w: CONTENT_W, h: 0.25,
        fontSize: 10, fontFace: "Arial", bold: true, color: ACCENT, align: "left", valign: "top",
        charSpacing: 3,
      });
    }

    // Headline
    const hSize = headlineFontSize(headline);
    slide.addText(headline, {
      x: MARGIN_L, y: categoryLabel ? 0.55 : 0.5, w: CONTENT_W, h: 0.7,
      fontSize: hSize, fontFace: "Arial", bold: true, color: FG, align: "left", valign: "top",
    });

    // Accent line
    slide.addShape(pptx.ShapeType.rect, { x: MARGIN_L, y: 1.2, w: 1.5, h: 0.025, fill: { color: ACCENT } });

    // Subheadline
    if (subheadline) {
      slide.addText(subheadline, {
        x: MARGIN_L, y: 1.4, w: CONTENT_W, h: 0.5,
        fontSize: 18, fontFace: "Arial", color: MUTED_TEXT, align: "left", valign: "top",
      });
    }

    // Body content from bodyContent array only
    const bodyTop = subheadline ? 2.0 : 1.6;
    if (bodyContent.length > 0) {
      const bulletRows = bodyContent.slice(0, 12).map((line: string) => ({
        text: line.replace(/^[-•*]\s*/, ""),
        options: {
          fontSize: 14, fontFace: "Arial", color: FG,
          bullet: { code: "2022", color: ACCENT },
          lineSpacingMultiple: 1.5, paraSpaceAfter: 6,
        },
      }));
      slide.addText(bulletRows as any, { x: MARGIN_L, y: bodyTop, w: CONTENT_W, h: 3.2, valign: "top" });
    }

    // Closing statement (bottom of slide)
    if (closingStatement) {
      slide.addText(closingStatement, {
        x: MARGIN_L, y: 6.4, w: CONTENT_W, h: 0.4,
        fontSize: 12, fontFace: "Arial", bold: true, color: ACCENT, align: "left", valign: "top",
      });
    }

    // Speaker notes (with layout recommendation appended)
    const notesText = [speakerNotes, layoutRecommendation ? `\n\n[Layout: ${layoutRecommendation}]` : ""].join("");
    if (notesText.trim()) {
      slide.addNotes(notesText.trim());
    }

    if (!isPro) slide.addText("Generated by Rhetoric", { x: MARGIN_L, y: 5.1, w: 3, fontSize: 8, fontFace: "Arial", color: MUTED, align: "left" });
  }

  await pptx.writeFile({ fileName: `${title.replace(/[^a-zA-Z0-9 ]/g, "")}.pptx` });
}
