import type { NarrativeOutputData } from "@/types/narrative";
import type { DeckTheme } from "@/components/SlidePreview";
import { resolveLayout } from "@/lib/slideLayouts";
import { computeLayout, parseSlide, S, type El } from "@/lib/slideLayoutEngine";

interface ExportOptions { output: NarrativeOutputData; isPro: boolean; excludedSlides: Set<number>; slideOrder: number[]; deckTheme: DeckTheme; }
type TC = Record<string, string>;

function getThemeColors(theme: DeckTheme): TC {
  const strip = (h: string) => h.replace("#", "");
  if (theme.scheme === "light") return { bg:"ffffff", fg:"334155", primary:"3b82f6", cat:"3b82f6", head:"1e293b", body:"475569", sub:"64748b", close:"3b82f6", accent:"e2e8f0", border:"e2e8f0" };
  if (theme.scheme === "custom") {
    const bg = theme.secondary || "#0b0f14"; const b = parseInt(bg.replace("#",""),16); const il = b > 0x888888;
    return { bg:strip(bg), fg:il?"334155":"cbd5e1", primary:strip(theme.primary||"#3b82f6"), cat:strip(theme.primary||"#60a5fa"), head:il?"1e293b":"e2e8f0", body:il?"475569":"cbd5e1", sub:il?"64748b":"94a3b8", close:strip(theme.primary||"#60a5fa"), accent:strip(theme.accent||"#1e3a5f"), border:il?"e2e8f0":"1e3a5f" };
  }
  return { bg:"0b0f14", fg:"cbd5e1", primary:"3b82f6", cat:"60a5fa", head:"e2e8f0", body:"cbd5e1", sub:"94a3b8", close:"60a5fa", accent:"1e3a5f", border:"1e3a5f" };
}

function color(key: string, tc: TC): string {
  if (key.startsWith("#")) return key.replace("#","");
  if (key.includes(":")) return tc[key.split(":")[0]] || "cccccc";
  return tc[key] || "cccccc";
}

function fillObj(key: string, tc: TC): any {
  if (key.includes(":")) {
    const [base, op] = key.split(":");
    return { color: tc[base] || "cccccc", transparency: Math.round((1 - parseFloat(op)) * 100) };
  }
  return { color: color(key, tc) };
}

// ── Render one element to a PptxGenJS slide ──
function render(el: El, slide: any, pptx: any, tc: TC) {
  switch (el.t) {
    case "text":
      slide.addText(el.text, {
        x:el.x, y:el.y, w:el.w, h:el.h, fontSize:el.pt, fontFace:"Arial",
        bold:el.bold||false, color:color(el.color,tc),
        align:el.align||"left", valign:el.valign||"top", charSpacing:el.spacing,
      });
      break;

    case "bullets":
      slide.addText(
        el.items.map(t => ({ text:t, options:{ fontSize:el.pt, fontFace:"Arial", color:color(el.color,tc), bullet:{code:"2022",color:color(el.bulletColor,tc)}, lineSpacingMultiple:el.lineH||1.5, paraSpaceAfter:3 } })),
        { x:el.x, y:el.y, w:el.w, h:el.h, valign:"top" }
      );
      break;

    case "rect":
      slide.addShape(pptx.ShapeType.rect, {
        x:el.x, y:el.y, w:el.w, h:el.h,
        fill: el.fill ? fillObj(el.fill, tc) : {type:"none"},
        line: el.stroke ? {color:color(el.stroke,tc), width:el.sw||1} : undefined,
        rectRadius: el.r,
      });
      break;

    case "ellipse":
      slide.addShape(pptx.ShapeType.ellipse, {
        x:el.cx-el.rx, y:el.cy-el.ry, w:el.rx*2, h:el.ry*2,
        fill: el.fill ? fillObj(el.fill, tc) : {type:"none"},
        line: el.stroke ? {color:color(el.stroke,tc), width:el.sw||1} : undefined,
      });
      break;

    case "line":
      slide.addShape(pptx.ShapeType.rect, {
        x:Math.min(el.x1,el.x2), y:Math.min(el.y1,el.y2),
        w:Math.abs(el.x2-el.x1)||0.015, h:Math.abs(el.y2-el.y1)||0.015,
        fill:{color:color(el.color,tc)},
      });
      break;
  }
}

// ── Main export ──
export async function exportPptx({ output, isPro, excludedSlides, slideOrder, deckTheme }: ExportOptions) {
  const PptxGenJS = (await import("pptxgenjs")).default;
  const pptx = new PptxGenJS();
  const title = (output as any).title || "Narrative Deck";
  pptx.author = "Rhetoric"; pptx.title = title; pptx.layout = "LAYOUT_16x9";
  const tc = getThemeColors(deckTheme);

  // Title slide
  const ts = pptx.addSlide(); ts.background = { color: tc.bg };
  ts.addShape(pptx.ShapeType.rect, { x:0, y:0, w:S.W, h:0.05, fill:{color:tc.primary} });
  ts.addShape(pptx.ShapeType.rect, { x:0, y:S.H-0.05, w:S.W, h:0.05, fill:{color:tc.primary} });
  ts.addText(title, { x:0.8, y:1.5, w:8.4, h:1.4, fontSize:26, fontFace:"Arial", bold:true, color:tc.head, align:"center", valign:"middle" });
  ts.addText(output.mode.replace(/_/g," ").toUpperCase(), { x:0.8, y:3.0, w:8.4, fontSize:10, fontFace:"Arial", color:tc.sub, align:"center", charSpacing:5 });
  if (!isPro) ts.addText("Generated by Rhetoric", { x:0.8, y:4.6, w:8.4, fontSize:8, fontFace:"Arial", color:tc.sub, align:"center" });

  // Content slides
  const d = (output.data || (output as any).supporting || {}) as any;
  const del = (output as any).deliverable || {};
  const fw = d.deckFramework || del.deckFramework || d.boardDeckOutline || del.boardDeckOutline || [];
  const ordered = slideOrder.length > 0 ? slideOrder : fw.map((_:any, i:number) => i);
  const active = ordered.filter((i:number) => !excludedSlides.has(i));

  for (const idx of active) {
    const raw = fw[idx]; if (!raw) continue;
    const data = parseSlide(raw);
    const layout = resolveLayout(raw?.layoutRecommendation, raw?.selectedLayout, raw?.categoryLabel, raw?.metadata?.dataPoints);

    const slide = pptx.addSlide(); slide.background = { color: tc.bg };

    for (const el of computeLayout(data, layout)) render(el, slide, pptx, tc);

    const notes = raw?.speakerNotes || "";
    if (notes.trim()) slide.addNotes(notes.trim());
    if (!isPro) slide.addText("Generated by Rhetoric", { x:S.ML, y:S.H-0.25, w:3, fontSize:7, fontFace:"Arial", color:tc.sub, align:"left" });
  }

  await pptx.writeFile({ fileName: `${title.replace(/[^a-zA-Z0-9 ]/g,"")}.pptx` });
}