import { useState, useRef, useEffect } from "react";
import { Download, FileText, FileDown, Presentation, File, ChevronDown } from "lucide-react";
import { toast } from "sonner";
import type { NarrativeOutputData } from "@/types/narrative";

interface Props {
  output: NarrativeOutputData;
  isPro: boolean;
  buildTabs: (output: NarrativeOutputData) => { key: string; label: string; sections: { key: string; path: string; label: string; content: string }[] }[];
}

export function ExportDropdown({ output, isPro, buildTabs }: Props) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  const tabs = buildTabs(output);

  const getAllContent = () => {
    return tabs.map(tab => {
      const sectionContent = tab.sections.map(s => `### ${s.label}\n\n${s.content}`).join("\n\n---\n\n");
      return `## ${tab.label}\n\n${sectionContent}`;
    }).join("\n\n===\n\n");
  };

  const exportPptx = async () => {
    if (!isPro) { toast.error("Export is available on Pro."); return; }
    setOpen(false);
    try {
      const PptxGenJS = (await import("pptxgenjs")).default;
      const pptx = new PptxGenJS();
      pptx.author = "Rhetoric";
      pptx.title = (output as any).title || "Narrative Deck";
      pptx.layout = "LAYOUT_16x9";

      // Color constants
      const BG = "0b0f14";
      const FG = "dce0e8";
      const MUTED = "6b7280";
      const ACCENT = "3b82f6";
      const ACCENT_DIM = "1e3a5f";

      // Title slide
      const titleSlide = pptx.addSlide();
      titleSlide.background = { color: BG };
      titleSlide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: "100%", h: 0.04, fill: { color: ACCENT } });
      titleSlide.addText((output as any).title || "Narrative Deck", {
        x: 0.8, y: 2, w: 8.4, h: 1.5, fontSize: 40, fontFace: "Arial", bold: true, color: FG, align: "center",
      });
      titleSlide.addText(output.mode.replace(/_/g, " ").toUpperCase(), {
        x: 0.8, y: 3.6, w: 8.4, fontSize: 14, fontFace: "Arial", color: ACCENT, align: "center", charSpacing: 4,
      });
      titleSlide.addText("Generated by Rhetoric", {
        x: 0.8, y: 5, w: 8.4, fontSize: 10, fontFace: "Arial", color: MUTED, align: "center",
      });

      // Content slides - vary layouts
      const layouts = ["full", "split", "bullets", "headline-body"];
      let layoutIdx = 0;

      for (const tab of tabs) {
        for (const section of tab.sections) {
          if (!section.content || section.content.trim().length === 0) continue;
          const slide = pptx.addSlide();
          slide.background = { color: BG };
          const layout = layouts[layoutIdx % layouts.length];
          layoutIdx++;

          // Top accent bar
          slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: "100%", h: 0.04, fill: { color: ACCENT } });

          // Tab label as breadcrumb
          slide.addText(tab.label.toUpperCase(), {
            x: 0.6, y: 0.3, w: 4, fontSize: 9, fontFace: "Arial", color: MUTED, charSpacing: 3,
          });

          const lines = section.content.split("\n").filter(l => l.trim());
          const bodyText = lines.join("\n");
          const isBulletContent = lines.length >= 3 && lines.every(l => l.length < 200);

          if (layout === "split" && lines.length > 2) {
            // Split layout: headline left, body right
            slide.addText(section.label, {
              x: 0.6, y: 0.8, w: 3.5, h: 1, fontSize: 28, fontFace: "Arial", bold: true, color: FG, valign: "top",
            });
            slide.addShape(pptx.ShapeType.rect, { x: 4.4, y: 0.8, w: 0.02, h: 3.8, fill: { color: ACCENT_DIM } });
            slide.addText(bodyText, {
              x: 4.8, y: 0.8, w: 4.6, h: 4.2, fontSize: 13, fontFace: "Arial", color: FG, lineSpacingMultiple: 1.4, valign: "top",
            });
          } else if ((layout === "bullets" || isBulletContent) && lines.length >= 3) {
            // Bullet layout
            slide.addText(section.label, {
              x: 0.6, y: 0.7, w: 8.8, fontSize: 30, fontFace: "Arial", bold: true, color: FG,
            });
            const bulletRows = lines.map(line => ({
              text: line.replace(/^[-•*]\s*/, ""),
              options: { fontSize: 14, fontFace: "Arial", color: FG, bullet: { code: "2022", color: ACCENT }, lineSpacingMultiple: 1.5, paraSpaceAfter: 6 },
            }));
            slide.addText(bulletRows as any, {
              x: 0.8, y: 1.6, w: 8.4, h: 3.6, valign: "top",
            });
          } else if (layout === "headline-body") {
            // Large headline + smaller body
            const headline = lines[0] || section.label;
            const rest = lines.slice(1).join("\n");
            slide.addText(headline, {
              x: 0.6, y: 0.8, w: 8.8, h: 1.2, fontSize: 36, fontFace: "Arial", bold: true, color: FG, valign: "top",
            });
            slide.addShape(pptx.ShapeType.rect, { x: 0.6, y: 2.2, w: 2, h: 0.03, fill: { color: ACCENT } });
            if (rest) {
              slide.addText(rest, {
                x: 0.6, y: 2.6, w: 8.8, h: 2.8, fontSize: 14, fontFace: "Arial", color: FG, lineSpacingMultiple: 1.4, valign: "top",
              });
            }
          } else {
            // Full content layout
            slide.addText(section.label, {
              x: 0.6, y: 0.7, w: 8.8, fontSize: 32, fontFace: "Arial", bold: true, color: FG,
            });
            slide.addText(bodyText, {
              x: 0.6, y: 1.6, w: 8.8, h: 3.6, fontSize: 14, fontFace: "Arial", color: FG, lineSpacingMultiple: 1.4, valign: "top",
            });
          }

          // Slide footer
          slide.addText(section.label, {
            x: 0.6, y: 5.1, w: 4, fontSize: 8, fontFace: "Arial", color: MUTED,
          });
        }
      }

      await pptx.writeFile({ fileName: `${(output as any).title || "Rhetoric_Deck"}.pptx` });
      toast.success("Deck exported as PowerPoint.");
    } catch {
      toast.error("Export failed.");
    }
  };

  const exportPdf = async () => {
    if (!isPro) { toast.error("PDF export is available on Pro."); return; }
    setOpen(false);
    // Use browser print as PDF
    const content = getAllContent();
    const win = window.open("", "_blank");
    if (!win) { toast.error("Please allow popups."); return; }
    win.document.write(`
      <html><head><title>${(output as any).title || "Rhetoric Export"}</title>
      <style>body{font-family:Arial,sans-serif;max-width:700px;margin:40px auto;color:#222;line-height:1.6}
      h2{border-bottom:2px solid #3b82f6;padding-bottom:8px;margin-top:32px}
      h3{color:#444;margin-top:20px}hr{border:none;border-top:1px solid #ddd;margin:24px 0}
      pre{white-space:pre-wrap}</style></head>
      <body><h1>${(output as any).title || "Narrative Export"}</h1><pre>${content}</pre></body></html>
    `);
    win.document.close();
    setTimeout(() => win.print(), 500);
    toast.success("PDF export opened in new tab.");
  };

  const exportMarkdown = () => {
    setOpen(false);
    const content = `# ${(output as any).title || "Narrative Export"}\n\n${getAllContent()}`;
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${(output as any).title || "Rhetoric_Export"}.md`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Exported as Markdown.");
  };

  const menuItems = [
    { icon: Presentation, label: "PowerPoint (.pptx)", onClick: exportPptx, pro: true },
    { icon: FileDown, label: "PDF (Print)", onClick: exportPdf, pro: true },
    { icon: FileText, label: "Markdown (.md)", onClick: exportMarkdown, pro: false },
    { icon: File, label: "Google Slides", onClick: () => { setOpen(false); toast.info("Google Slides export coming soon."); }, soon: true },
    { icon: File, label: "Google Docs", onClick: () => { setOpen(false); toast.info("Google Docs export coming soon."); }, soon: true },
  ];

  return (
    <div className="relative" ref={ref}>
      <button
        onClick={() => setOpen(!open)}
        className="text-xs px-3 py-1.5 border border-border rounded-sm text-muted-foreground hover:text-foreground transition-colors flex items-center gap-1.5"
      >
        <Download className="h-3 w-3" />Export<ChevronDown className="h-3 w-3" />
      </button>
      {open && (
        <div className="absolute top-full mt-1 right-0 w-56 bg-card border border-border rounded-sm shadow-lg z-30 animate-fade-in py-1">
          {menuItems.map((item) => (
            <button
              key={item.label}
              onClick={item.onClick}
              className="w-full text-left text-xs px-3 py-2 hover:bg-accent transition-colors flex items-center gap-2 text-foreground"
            >
              <item.icon className="h-3.5 w-3.5 text-muted-foreground" />
              {item.label}
              {item.soon && <span className="ml-auto text-[10px] text-muted-foreground bg-muted px-1.5 py-0.5 rounded-sm">Soon</span>}
              {item.pro && !isPro && <span className="ml-auto text-[10px] text-electric">Pro</span>}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
